AutoHub/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AutoHub.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Authorize(Roles = "Admin")]
	[Route("Admin")]
	public class HomeController : Controller
	{
		[Route("")]
		[Route("Index")]
		public IActionResult Index()
		{
			return View();
		}
	}
}

AutoHub/Areas/Admin/Controllers/UserManageController.cs
using AutoHub.Areas.Admin.ViewModels;
using AutoHub.Data.Migrations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AutoHub.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Authorize(Roles = "Admin")]
	public class UserManageController : Controller
	{
		private readonly UserManager<IdentityUser> _userManager;
		private readonly RoleManager<IdentityRole> _roleManager;

        public UserManageController(UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            this._userManager = userManager;
            this._roleManager = roleManager;
        }

		[HttpGet]
        public async Task<IActionResult> Index()
		{
			var users = _userManager.Users.ToList();
			var userViewModels = new List<UserManageViewModel>();

			foreach (var user in users) 
			{
				var roles = await _userManager.GetRolesAsync(user);
				userViewModels.Add(new UserManageViewModel
				{
					UserId = user.Id,
					Email = user.Email ?? string.Empty,
					UserName = user.UserName ?? string.Empty,
					UserRoles = roles.ToList()
				});
			}
			return View("~/Areas/Admin/Views/UserManagement/Index.cshtml", userViewModels);

        }

        [HttpPost]
        public async Task<IActionResult> AssignRole(string userId, string roleId)
        {
            var user = await _userManager.FindByIdAsync(userId);

            if (user != null)
            {
                var roleExist = await _roleManager.RoleExistsAsync(roleId);

				if (roleExist)
				{
					if (!await _userManager.IsInRoleAsync(user, roleId))
					{
						var result = await _userManager.AddToRoleAsync(user, roleId);
					}
				}
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
		public async Task<IActionResult> RemoveRole(string userId, string roleName)
		{
			var user = await _userManager.FindByIdAsync(userId);

			if (user != null && await _roleManager.RoleExistsAsync(roleName))
			{
				await _userManager.RemoveFromRoleAsync(user, roleName);
			}
			return RedirectToAction(nameof(Index));
		}

		[HttpPost]
		public async Task<IActionResult> DeleteUser(string userId)
		{
			var user = await _userManager.FindByIdAsync(userId);

			if (user != null)
			{
				await _userManager.DeleteAsync(user);
			}
			return RedirectToAction(nameof(Index));
		}
	}
}

AutoHub/Controllers/HomeController.cs
using AutoHub.Models;
using AutoHub.Web.ViewModels.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AutoHub.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;

        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Error403()
        {
            return View();
        }

        [HttpGet("/Home/Error/{statusCode?}")]
        public IActionResult Error(int? statusCode = null)
        {
          
            if (statusCode == 500)
            {
                return this.View("Error500");
            }
            else if (statusCode == 404)
            {
                return this.View("Error404");
            }
            else if (statusCode == 403)
            {
                return this.View("Error403");
            }

            return View("Error500");
        }

        public IActionResult Test500()
        {
            throw new ArgumentException();
        }
    }
}

AutoHub/Areas/Admin/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Admin Management";

    Layout = "~/Views/Shared/_Layout.cshtml"; 
}

<div class="container text-center mt-5">
    <h1 class="display-4 mb-4">Admin Management</h1>
    <hr />
    <div class="mt-4">
        <h3>Manage</h3>
        <div class="d-flex justify-content-center flex-wrap mt-3">
            <a asp-area="Admin" asp-controller="UserManage" asp-action="Index" class="btn btn-primary m-2" style="width: 150px;">User Roles</a>
            <a href="/Brand" class="btn btn-primary m-2" style="width: 150px;">Brands</a>
            <a href="/Model" class="btn btn-primary m-2" style="width: 150px;">Models</a>
            <a href="/Engine" class="btn btn-primary m-2" style="width: 150px;">Engines</a>
            <a href="/Gearbox" class="btn btn-primary m-2" style="width: 150px;">Gearboxes</a>
            <a href="/HydraulicSystem" class="btn btn-primary m-2" style="width: 150px;">HydraulicSystem</a>
            <a href="/Product" class="btn btn-primary m-2" style="width: 150px;">Products</a>
        </div>
    </div>
</div>