AutoHub/Controllers/BrandController.cs
using AutoHub.Data;
using AutoHub.Data.Models;
using AutoHub.Infrastructure;
using AutoHub.Infrastructure.DTOs;
using AutoHub.Infrastructure.Models;
using AutoHub.Infrastructure.Repositories.Interfaces;
using AutoHub.Infrastructure.Services.Interfaces;
using AutoHub.Web.ViewModels.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Globalization;

namespace AutoHub.Controllers
{
    public class BrandController : Controller
    {
        private readonly IBrandService _brandService;

        public BrandController(IBrandService brandService)
        {
            _brandService = brandService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string? searchQuery, int currentPage = 1)
        {
            var brands = await _brandService.GetAllBrandsAsync();

            //Search filter
            if (!string.IsNullOrEmpty(searchQuery))
            {
                brands = brands.Where(b => b.Name.Contains(searchQuery, StringComparison.OrdinalIgnoreCase));                             
            }


            //Pagination
            int entitiesPerPage = 3;
            int totalBrands = brands.Count();
            var pagedBrands = brands.Skip((currentPage - 1) * entitiesPerPage)
                                    .Take(entitiesPerPage);

            var viewModel = new SearchPagination
            {
                Brands = pagedBrands.Select(b => new BrandDto
                {
                    Id = b.Id,
                    Name = b.Name,
                    FoundedBy = b.FoundedBy,
                    FoundedDate = b.FoundedDate,
                    Description = b.Description,
                    ImageUrl = b.ImageUrl
                }),
                SearchQuery = searchQuery,
                CurrentPage = currentPage,
                EntitiesPerPage = entitiesPerPage,
                TotalPages = (int)Math.Ceiling((double)totalBrands / entitiesPerPage),
            };
            return View(viewModel);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Create() 
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(BrandViewModel brandModel) 
        {
            if (!ModelState.IsValid) 
            {
                return View(brandModel);
            }

            bool isFoundedDateValid = DateTime
                 .TryParseExact(
                brandModel.FoundedDate, 
                "MM/dd/yyyy", 
                CultureInfo.InvariantCulture, 
                DateTimeStyles.None,
                out DateTime foundedDate);

            if (!isFoundedDateValid)
            {
                this.ModelState.AddModelError(nameof(brandModel.FoundedDate), "The date founded must be the following format MM/dd/yyyy");
                return this.View(brandModel);
            }

            var brandDto = new BrandDto
            {
                Name = brandModel.Name,
                FoundedBy = brandModel.FoundedBy,
                FoundedDate = foundedDate,
                Description = brandModel.Description,
                ImageUrl = brandModel.ImageUrl
            };

            await _brandService.AddBrandAsync(brandDto);
           
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Details(string id) 
        {
            bool isIdValid = Guid.TryParse(id, out Guid guidId);
            if (!isIdValid) 
            {
                return this.RedirectToAction(nameof(Index));
            }

            var brand = await _brandService.GetBrandByIdAsync(guidId);

            if (brand == null) 
            {
                return RedirectToAction(nameof(Index));
            }

            return View(brand);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete (string id)
        {
            bool isIdValid = Guid.TryParse(id, out Guid guidId);
            if (!isIdValid)
            {
                return this.RedirectToAction(nameof(Index));
            }

            var brand = await _brandService.GetBrandByIdAsync(guidId);

            if (brand == null) 
            {
                return RedirectToAction(nameof(Index));
            }

            var brandModel = new BrandDto
            {
                Id = brand.Id,
                Name = brand.Name,
                FoundedBy = brand.FoundedBy,
                FoundedDate = brand.FoundedDate,
                Description = brand.Description,
                ImageUrl = brand.ImageUrl
            };

            return View(brandModel);
        }
        
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete (Guid id)
        {
            try
            {
                await _brandService.DeleteBrandAsync(id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                return NotFound();
            }
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit (string id)
        {
            bool isIdValid = Guid.TryParse(id, out Guid guidId);
            if (!isIdValid)
            {
                return this.RedirectToAction(nameof(Index));
            }

          
            var brand = await _brandService.GetBrandByIdAsync(guidId);

            if (brand == null) 
            {
                return RedirectToAction(nameof(Index));
            }

            var brandModel = new BrandViewModel
            {
                Id = brand.Id,
                Name = brand.Name,
                FoundedBy = brand.FoundedBy,
                FoundedDate = brand.FoundedDate.ToString("MM/dd/yyyy"),
                Description = brand.Description,
                ImageUrl = brand.ImageUrl
            };

            return View(brandModel);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(BrandViewModel model)
        {

            bool isFoundedDateValid = DateTime
                .TryParseExact(
               model.FoundedDate,
               "MM/dd/yyyy",
               CultureInfo.InvariantCulture,
               DateTimeStyles.None,
               out DateTime foundedDate);

            if (!isFoundedDateValid)
            {
                this.ModelState.AddModelError(nameof(model.FoundedDate), "The date founded must be the following format MM/dd/yyyy");
                return this.View(model);
            }

            if (ModelState.IsValid) 
            {
                var brandModelUpdate = new BrandDto
                {
                    Id = model.Id,
                    Name = model.Name,
                    FoundedBy = model.FoundedBy,
                    FoundedDate = foundedDate,
                    Description = model.Description,
                    ImageUrl = model.ImageUrl
                };

                await _brandService.UpdateBrandAsync(brandModelUpdate);
                return RedirectToAction("Details", new { id = model.Id });
            }
            return View(model);
        }
    }
}

AutoHub/Controllers/ModelController.cs
using AutoHub.Data;
using AutoHub.Data.Models;
using AutoHub.Infrastructure.DTOs;
using AutoHub.Infrastructure.Models;
using AutoHub.Infrastructure.Repositories.Interfaces;
using AutoHub.Infrastructure.Services;
using AutoHub.Infrastructure.Services.Interfaces;
using AutoHub.Web.ViewModels.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Globalization;

namespace AutoHub.Controllers
{
    public class ModelController : Controller
    {
        private readonly IModelService _modelService;
        private readonly IBrandRepository _brandRepository;
        private readonly IEngineRepository _engineRepository;

        public ModelController(IModelService modelService,IBrandRepository brandRepository, IEngineRepository engineRepository)
        {
            _modelService = modelService;
            _brandRepository = brandRepository;
            _engineRepository = engineRepository;
        }

        [HttpGet]
        public async Task <IActionResult> Index(string? searchQuery, string? selectedBrand, int currentPage = 1)
        {
            
            var models = await _modelService.GetAllModelsAsync();

            if (!string.IsNullOrEmpty(searchQuery))
            {
                models = models.Where(m => m.Name.Contains(searchQuery, StringComparison.OrdinalIgnoreCase));
            }

            if (!string.IsNullOrEmpty(selectedBrand))
            {
                models = models.Where(m => m.BrandId.ToString() == selectedBrand);
            }

            var brands = await _brandRepository.GetAllAsync();

            int entitiesPerPage = 3;
            int totalModels = models.Count();
            var pagedModels = models.Skip((currentPage - 1) * entitiesPerPage)
                                    .Take(entitiesPerPage);

            var viewModel = new SearchPagination
            {
                Models = pagedModels.Select(m => new ModelDto
                {
                   Id = m.Id,
                   Name = m.Name,
                   Year = m.Year,
                   HorsePower = m.HorsePower,
                   FuelType = m.FuelType,
                   GasConsumption = m.GasConsumption,
                   Description = m.Description,
                   ImageUrl = m.ImageUrl,
                   BrandId = m.BrandId,
                   BrandName = m.BrandName
                }),
                SearchQuery = searchQuery,
                SelectedBrand = selectedBrand,
                Brands = brands.Select(b => new BrandDto
                {
                    Id = b.Id,
                    Name = b.Name
                }),
                CurrentPage = currentPage,
                EntitiesPerPage = entitiesPerPage,
                TotalPages = (int)Math.Ceiling((double)totalModels / entitiesPerPage)
            };

            return View(viewModel);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create() 
        {
            var brands = await _brandRepository.GetAllAsync();

            var brandViewModel = new ModelViewModel
            {
                Brands = brands.ToList()
            };
            return View(brandViewModel);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(ModelViewModel model) 
        {
            if (ModelState.IsValid) 
            {
                var modelDto = new ModelDto
                {
                    Name = model.Name,
                    Year = model.Year,
                    HorsePower = model.HorsePower,
                    FuelType = model.FuelType,
                    GasConsumption = model.GasConsumption,
                    Description = model.Description,
                    ImageUrl = model.ImageUrl,
                    BrandId = model.SelectedBrand
                };
               
                await _modelService.AddModelAsync(modelDto);
                
                return RedirectToAction(nameof(Index));
            }

            model.Brands = (await _brandRepository.GetAllAsync()).ToList();

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Details(string id) 
        {
            bool isValid = Guid.TryParse(id, out Guid guidId);
            if (!isValid) 
            {
                return this.RedirectToAction(nameof(Index));
            }

            var model = await _modelService.GetModelByIdAsync(guidId);

            if (model == null) 
            {
                return RedirectToAction(nameof(Index));
            }
                
                
            return this.View(model);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete (string id)
        {
            bool isIdValid = Guid.TryParse(id, out Guid guidId);
            if (!isIdValid)
            {
                return this.RedirectToAction(nameof(Index));
            }

            var model = await _modelService.GetModelByIdAsync(guidId);

            if (model == null)
            {
                return RedirectToAction(nameof(Index));
            }

            var modelDto = new ModelDto
            {
                Id = model.Id,
                Name = model.Name,
                Year = model.Year,
                HorsePower = model.HorsePower,
                FuelType = model.FuelType,
                GasConsumption = model.GasConsumption,
                Description = model.Description,
                ImageUrl = model.ImageUrl,
                BrandId = model.BrandId,
                BrandName = model.BrandName
            };
            return View(modelDto);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var engines = await _modelService.GetEnginesByModelIdAsync(id);
            var gearboxes = await _modelService.GetGearboxesByModelIdAsync(id);

            foreach (var engine in engines)
            {
                await _modelService.DeleteEngineAsync(engine);
            }

            foreach (var gearbox in gearboxes)
            {
                await _modelService.DeleteGearboxAsync(gearbox);
            }

            try
            {
                await _modelService.DeleteModelAsync(id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                return NotFound();
            }
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(string id)
        {
            bool isIdValid = Guid.TryParse(id, out Guid guidId);
            if (!isIdValid)
            {
                return this.RedirectToAction(nameof(Index));
            }


            var model = await _modelService.GetModelByIdAsync(guidId);
            var brands = await _brandRepository.GetAllAsync();


            if (model == null)
            {
                return RedirectToAction(nameof(Index));
            }

            var brandViewModel = new ModelViewModel
            {
                Brands = brands.ToList()
            };

            var modelDto = new ModelViewModel
            {
                Id = model.Id,
                Name = model.Name,
                Year = model.Year,
                HorsePower = model.HorsePower,
                FuelType = model.FuelType,
                GasConsumption = model.GasConsumption,
                Description = model.Description,
                ImageUrl = model.ImageUrl,
                SelectedBrand = model.BrandId,
                Brands = brands.ToList()
            };

            return View(modelDto);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(ModelViewModel model)
        {
            if (ModelState.IsValid)
            {
                var modelUpdate = new ModelDto
                {
                    Id = model.Id,
                    Name = model.Name,
                    Year = model.Year,
                    HorsePower = model.HorsePower,
                    FuelType = model.FuelType,
                    GasConsumption = model.GasConsumption,
                    Description = model.Description,
                    ImageUrl = model.ImageUrl,
                    BrandId = model.SelectedBrand
                };

                await _modelService.UpdateModelAsync(modelUpdate);
                return RedirectToAction("Details", new { id = model.Id });
            }
            return View(model);
        }
    }
}

AutoHub/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AutoHub</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AutoHub.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AutoHub</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-extra-dark" asp-area="" asp-controller="Admin" asp-action="Index">AdminManagement</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Brand" asp-action="Index">Brands</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Model" asp-action="Index">Models</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Parts
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="Engine" asp-action="Index">View Engines</a>
                                <a class="dropdown-item" asp-controller="Gearbox" asp-action="Index">View Gearboxes</a>
                                <a class="dropdown-item" asp-controller="HydraulicSystem" asp-action="Index">View Hydraulic System</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Marketplace</a>
                        </li>
                        <li class="nav-item">
                            @if (!User.IsInRole("Admin"))
                            {
                                <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Cart">My Cart</a>
                            }
                        </li>
                    </ul>
                    <partial name="_LoginPartial"/>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AutoHub
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>