AutoHub/Controllers/EngineController.cs
using AutoHub.Data;
using AutoHub.Data.Models;
using AutoHub.Infrastructure.DTOs;
using AutoHub.Infrastructure.Models;
using AutoHub.Infrastructure.Repositories.Interfaces;
using AutoHub.Infrastructure.Services.Interfaces;
using AutoHub.Web.ViewModels.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Cryptography.Xml;

namespace AutoHub.Controllers
{
    public class EngineController : Controller
    {
        private readonly IEngineService _engineService;
        private readonly IBaseRepository<Model> _modelRepository;
        private readonly IBaseRepository<Brand> _brandRepository;

        public EngineController(IEngineService engineService, IBaseRepository<Model> modelRepository, IBaseRepository<Brand> brandRepository)
        {
            _engineService = engineService;
            _modelRepository = modelRepository;
            _brandRepository = brandRepository;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string? searchQuery, string? selectedBrand, int currentPage = 1)
        {
            var engines = await _engineService.GetAllEnginesAsync();

            if (!string.IsNullOrEmpty(searchQuery))
            {
                engines = engines.Where(e => e.Name.Contains(searchQuery, StringComparison.OrdinalIgnoreCase));
            }

            if (!string.IsNullOrEmpty(selectedBrand))
            {
                engines = engines.Where(e => e.BrandId.ToString() == selectedBrand);
            }

            var brands = await _brandRepository.GetAllAsync();

            int entitiesPerPage = 3;
            int totalEngines = engines.Count();
            var pagedEngines = engines.Skip((currentPage - 1) * entitiesPerPage)
                                    .Take(entitiesPerPage);

            var viewModel = new SearchPagination
            {
                Engines = pagedEngines.Select(e => new EngineDto
                {
                    Id = e.Id,
                    Name = e.Name,
                    BrandId = e.BrandId,
                    BrandName = e.BrandName,
                    ModelId = e.ModelId,
                    ModelName = e.ModelName,
                    Cylinders = e.Cylinders,
                    ValveTrainDriveSystem = e.ValveTrainDriveSystem,
                    PowerOutput = e.PowerOutput,
                    Torque = e.Torque,
                    Rpm = e.Rpm,
                    YearsProduction = e.YearsProduction,
                    ImageUrl = e.ImageUrl
                }),
                SearchQuery = searchQuery,
                SelectedBrand = selectedBrand,
                CurrentPage = currentPage,
                Brands = brands.Select(b => new BrandDto
                {
                    Id = b.Id,
                    Name = b.Name
                }),
                EntitiesPerPage = entitiesPerPage,
                TotalPages = (int)Math.Ceiling((double)totalEngines / entitiesPerPage),
            };
            return View(viewModel);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create()
        {
            var brands = await _brandRepository.GetAllAsync();
            var models = await _modelRepository.GetAllAsync();

            var engineViewModel = new EngineViewModel
            {
                Brands = brands.ToList(),
                Models = models.ToList()
            };
            return View(engineViewModel);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(EngineViewModel model)
        {
            if (ModelState.IsValid)
            {
                var engineDto = new EngineDto
                {
                    Name = model.Name,
                    BrandId = model.Manufacturer,
                    ModelId = model.Application,
                    Cylinders = model.Cylinders,
                    ValveTrainDriveSystem = model.ValveTrainDriveSystem,
                    PowerOutput = model.PowerOutput,
                    Torque = model.Torque,
                    Rpm = model.Rpm,
                    ImageUrl = model.ImageUrl,
                    YearsProduction = model.YearsProduction
                };

                await _engineService.AddEngineAsync(engineDto);

                return RedirectToAction(nameof(Index));
            }

            model.Brands = (await _brandRepository.GetAllAsync()).ToList();
            model.Models = (await _modelRepository.GetAllAsync()).ToList();

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            bool isValid = Guid.TryParse(id, out Guid guidId);

            if (!isValid)
            {
                return RedirectToAction(nameof(Index));
            }

            var engines = await _engineService.GetEngineByIdAsync(guidId);

            if (engines == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return View(engines);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(string id)
        {
            bool isValid = Guid.TryParse(id, out Guid guidId);

            if (!isValid)
            {
                return RedirectToAction(nameof(Index));
            }

            var engine = await _engineService.GetEngineByIdAsync(guidId);

            if (engine == null)
            {
                throw new ArgumentException("Engine not found");
            }

            var engineDto = new EngineDto
            {
                Id = engine.Id,
                Name = engine.Name,
                BrandId = engine.BrandId,
                BrandName = engine.BrandName
            };

            return View(engineDto);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(Guid id)
        {
            try
            {
                await _engineService.DeleteEngineAsync(id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                throw new ArgumentException("Engine not found");
            }

        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit (string id)
        {
            bool isValid = Guid.TryParse(id, out Guid guidId);

            if (!isValid)
            {
                return RedirectToAction(nameof(Index));
            }

            var engine = await _engineService.GetEngineByIdAsync(guidId);

            var brands = await _brandRepository.GetAllAsync();
            var models = await _modelRepository.GetAllAsync();

            if (engine == null)
            {
                throw new ArgumentException("Engine not found");
            }

           
            var engineModel = new EngineViewModel
            {
                Id = engine.Id,
                Name = engine.Name,
                Manufacturer = engine.BrandId,
                Brands = brands.ToList(),
                Application = engine.ModelId,
                Models = models.ToList(),
                Cylinders = engine.Cylinders,
                ValveTrainDriveSystem = engine.ValveTrainDriveSystem,
                PowerOutput = engine.PowerOutput,
                Torque = engine.Torque,
                Rpm = engine.Rpm,
                ImageUrl = engine.ImageUrl,
                YearsProduction = engine.YearsProduction
            };

            return View(engineModel);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(EngineViewModel engineModel)
        {
            if (ModelState.IsValid) 
            {
                var engineUpdate = new EngineDto
                {
                    Id = engineModel.Id,
                    Name = engineModel.Name,
                    BrandId = engineModel.Manufacturer,
                    ModelId = engineModel.Application,
                    Cylinders = engineModel.Cylinders,
                    ValveTrainDriveSystem = engineModel.ValveTrainDriveSystem,
                    PowerOutput = engineModel.PowerOutput,
                    Torque = engineModel.Torque,
                    Rpm = engineModel.Rpm,
                    ImageUrl = engineModel.ImageUrl,
                    YearsProduction = engineModel.YearsProduction
                };

                await _engineService.UpdateEngineAsync(engineUpdate);
                return RedirectToAction("Details", new { id = engineModel.Id });
            }
            return View(engineModel);
        }
    }
}

AutoHub/Views/Engine/Create.cshtml
@using AutoHub.Web.ViewModels.Models
@model EngineViewModel

<h2>Add a New Engine</h2>

<form asp-action="Create" method="post">
    <div>
        <label for="Name">Engine Name</label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Manufacturer"></label>
        @Html.DropDownListFor(model => model.Manufacturer,
                 new SelectList(Model.Brands, "Id", "Name", Model.Manufacturer),
                 "Select a manufacturer", new { @class = "form-control" })

        <span asp-validation-for="Manufacturer"></span>
    </div>
    <div>
        <label asp-for="Application"></label>
        @Html.DropDownListFor(model => model.Application,
                 new SelectList(Model.Models, "Id", "Name", Model.Application),
                 "Select a model", new { @class = "form-control" })

        <span asp-validation-for="Application"></span>
    </div>
    <div>
        <label for="Cylinders">Cylinders</label>
        <small class="text-muted">Type in between 3 to 16</small>
        <input asp-for="Cylinders" class="form-control" />
        <span asp-validation-for="Cylinders" class="text-danger"></span>
    </div>
    <div>
        <label for="ValveTrainDriveSystem">ValveTrainDriveSystem</label>
        <small class="text-muted">Type in Chain,Belt or Gear</small>
        <input asp-for="ValveTrainDriveSystem" class="form-control" />
        <span asp-validation-for="ValveTrainDriveSystem" class="text-danger"></span>
    </div>
    <div>
        <label for="PowerOutput">PowerOutput</label>
        <small class="text-muted">Format: 125-300hp</small>
        <input asp-for="PowerOutput" class="form-control" />
        <span asp-validation-for="PowerOutput" class="text-danger"></span>
    </div>
    <div>
        <label for="Torque">Torque</label>
        <small class="text-muted">Format: 250-300Nm</small>
        <input asp-for="Torque" class="form-control" />
        <span asp-validation-for="Torque" class="text-danger"></span>
    </div>
    <div>
        <label for="Rpm">Rpm</label>
        <small class="text-muted">Format: 1250-3250Rpm</small>
        <input asp-for="Rpm" class="form-control" />
        <span asp-validation-for="Rpm" class="text-danger"></span>
    </div>
    <div>
        <label for="ImageUrl">ImageUrl</label>
        <input asp-for="ImageUrl" class="form-control" />
        <span asp-validation-for="ImageUrl" class="text-danger"></span>
    </div>
    <div>
        <label for="YearsProduction">YearsProduction</label>
        <small class="text-muted">Format: 2005-2016</small>
        <input asp-for="YearsProduction" class="form-control" />
        <span asp-validation-for="YearsProduction" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary mt-2">Create Engine</button>
</form>

<a asp-action="Index">Back to Engine List</a>

AutoHub/Views/Engine/Delete.cshtml
@using AutoHub.Infrastructure.DTOs
@model EngineDto



<h2>Delete Engine</h2>

<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title text-center">@Model.Name</h3>
                <p class="text-danger mt-3">Are you sure you want to delete @(Model.Name)?</p>
                <p class="text-danger mt-3">This model is related to the @(Model.BrandName)</p>
            </div>
            <div class="card-footer">
                <form asp-action="Delete" method="post">
                    <input type="hidden" asp-for="Id" />
                    <input type="hidden" asp-for="Name" />
                    <button type="submit" class="btn btn-danger">Confirm Delete</button>
                    <a asp-controller="Engine" asp-action="Index" asp-route-id="@Model.Id" class="btn btn-primary">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>

AutoHub/Views/Engine/Details.cshtml
@using AutoHub.Infrastructure.DTOs
@model EngineDto

<div class="container mt-4">

    <div class="row justify-content-center">
        <div class="col-md-8 text-center">
            <div class="card border-0">
                <img src="@Model.ImageUrl" alt="@Model.Name" class="img-fluid" style="max-width: 100%; height: min-content;">
            </div>
        </div>
    </div>


    <div class="row justify-content-center mt-3">
        <div class="col-md-8">
            <div class="card p-5">
                <h2 class="text-center">@Model.Name</h2>

                <p><strong>Brand:</strong> @Model.BrandName</p>
                <p><strong>Application:</strong> @Model.ModelName</p>
                <p><strong>Cylinders:</strong> @Model.Cylinders</p>
                <p><strong>ValveTrainDriveSystem:</strong> @Model.ValveTrainDriveSystem</p>
                <p><strong>PowerOutput:</strong> @Model.PowerOutput</p>
                <p><strong>Torque:</strong> @Model.Torque</p>
                <p><strong>RPM:</strong> @Model.Rpm</p>
                <p><strong>Years Produced:</strong> @Model.YearsProduction</p>
            </div>
        </div>
    </div>
</div>

<a asp-action="Index" class="btn btn-primary">Back to All Engines</a>

AutoHub/Views/Engine/Edit.cshtml
@using AutoHub.Web.ViewModels.Models
@model EngineViewModel

<h2>Edit Engine</h2>

<form asp-action="Edit" method="post">
    <div>
        <input type="hidden" asp-for="Id" />
    </div>
    <div>
        <label for="Engine Name">Engine Name</label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Manufacturer"></label>
        @Html.DropDownListFor(model => model.Manufacturer,
                 new SelectList(Model.Brands, "Id", "Name", Model.Manufacturer),
                 "Select a manufacturer", new { @class = "form-control" })

        <span asp-validation-for="Manufacturer"></span>
    </div>
    <div>
        <label asp-for="Application"></label>
        @Html.DropDownListFor(model => model.Application,
                 new SelectList(Model.Models, "Id", "Name", Model.Application),
                 "Select application", new { @class = "form-control" })

        <span asp-validation-for="Application"></span>
    </div>
    <div>
        <label for="Cylinders">Cylinders</label>
        <input asp-for="Cylinders" class="form-control" />
        <span asp-validation-for="Cylinders" class="text-danger"></span>
    </div>
    <div>
        <label for="ValveTrainDriveSystem">ValveTrainDriveSystem</label>
        <input asp-for="ValveTrainDriveSystem" class="form-control" />
        <span asp-validation-for="ValveTrainDriveSystem" class="text-danger"></span>
    </div>
    <div>
        <label for="PowerOutput">PowerOutput</label>
        <input asp-for="PowerOutput" class="form-control" />
        <span asp-validation-for="PowerOutput" class="text-danger"></span>
    </div>
    <div>
        <label for="Torque">Torque</label>
        <input asp-for="Torque" class="form-control" />
        <span asp-validation-for="Torque" class="text-danger"></span>
    </div>
    <div>
        <label for="Rpm">Rpm</label>
        <input asp-for="Rpm" class="form-control" />
        <span asp-validation-for="Rpm" class="text-danger"></span>
    </div>
    <div>
        <label for="ImageUrl">ImageUrl</label>
        <input asp-for="ImageUrl" class="form-control" />
        <span asp-validation-for="ImageUrl" class="text-danger"></span>
    </div>
    <div>
        <label for="YearsProduction">YearsProduction</label>
        <input asp-for="YearsProduction" class="form-control" />
        <span asp-validation-for="YearsProduction" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary mt-2">Save Changes</button>
</form>

<a asp-action="Index">Back to Engines</a>

AutoHub/Views/Engine/Index.cshtml
@using AutoHub.Infrastructure.Models
@using AutoHub.Infrastructure.DTOs
@model SearchPagination

<style>

    .btn {
        display: inline-block;
        padding: 5px 15px;
        text-align: center;
        vertical-align: middle;
        border-radius: 4px;
        min-width: 100px;
    }

    .custom-red {
        background-color: #c90404;
        color: white;
        border: none;
    }

    .custom-black {
        background-color: #000000;
        color: white;
        border: none;
    }
</style>


<h2 class="text-center">All Engines</h2>

<form method="get" asp-action="Index" class="mb-4">
    <div class="row">
        <div class="col">
            <div class="form-group">
                <label asp-for="SearchQuery">Search by Engine name</label>
                <input asp-for="SearchQuery" class="form-control" placeholder="Search by engine name..." />

                <label asp-for="SelectedBrand">Search by Brand</label>
                @Html.DropDownListFor(model => model.SelectedBrand,
                         new SelectList(Model.Brands, "Id", "Name", Model.SelectedBrand),
                         "Select a brand", new { @class = "form-control" })

                <span asp-validation-for="SelectedBrand"></span>
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Search</button>
    <a asp-action="Index" type="submit" class="btn btn-primary">Reset</a>
</form>


<div class="container">
    <div class="row">
        @foreach (EngineDto engines in Model.Engines)
        {
            <div class="col-md-4 mb-4">
                <div class="card text-center">
                    <img src="@engines.ImageUrl" alt="@engines.Name" class="card-img-top" style="max-height: 200px; object-fit: cover;" />
                    <div class="card-body">
                        <h5 class="card-title">@engines.Name</h5>
                        <a asp-action="Details" asp-route-id="@engines.Id" class="btn btn-primary">Details</a>
                        @if (User.IsInRole("Admin"))
                        {
                            <a asp-action="Delete" asp-route-id="@engines.Id" class="btn custom-red">Delete</a>
                            <a asp-action="Edit" asp-route-id="@engines.Id" class="btn custom-black">Edit</a>
                        }
                    </div>
                </div>
            </div>
        }
    </div>
</div>

@if (Model.TotalPages > 0 || User.IsInRole("Admin"))
{
    <div class="d-flex justify-content-between align-items-center mt-4">

        <div>
            <a asp-action="Index"
               asp-route-SearchQuery="@Model.SearchQuery"
               asp-route-CurrentPage="@(Model.CurrentPage > 1 ? Model.CurrentPage - 1 : 1)"
               class="btn btn-secondary @(Model.CurrentPage == 1 ? "disabled" : "")">
                Previous
            </a>

            <a asp-action="Index"
               asp-route-SearchQuery="@Model.SearchQuery"
               asp-route-CurrentPage="@(Model.CurrentPage < Model.TotalPages ? Model.CurrentPage + 1 : Model.TotalPages)"
               class="btn btn-secondary @(Model.CurrentPage == Model.TotalPages ? "disabled" : "")">
                Next
            </a>
        </div>

        @if (User.IsInRole("Admin"))
        {
            <a asp-action="Create" class="btn btn-primary">Add New Engine</a>
        }

    </div>
}


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}